CREATE TABLE IF NOT EXISTS  `pais`.tabelaPais(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `populacao` BIGINT NULL DEFAULT NULL,
  `area` DECIMAL(15,2) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
  );
  
